### PR TITLE
Fix tests, upgrade node-sass

### LINKED ISSUE #105: Incompatible with DocPad v6.80 and above
Plugin requires updating to CoffeeScript v2. This can be done automatically via running https://github.com/bevry/boundation on it.
If you would like the DocPad team to do it, then transfer the repo to the https://github.com/docpad organisation, and run the following:

npm owner add balupton docpad-plugin-assets
npm owner add bevryme docpad-plugin-assets

### PR DESCRIPTION
**Pull request by cattermo**
fixes #105 
* Upgrade node-sass
* Convert from coffeescript to js (resolved problem with tests)
* add eslint + fix lint errors

### CODE REVIEW

**Comment by cattermo** [comment]
@balupton Should I run `npm run our:release:prepare` and commit the new version as well?

Really hope you can accept the fix, I don't normally do open source but I use this plugin for an old hobby project that I hope to get running again.

Don't know why the coffeescript version would not work but thought it would be worth a try to convert to js and that seems to have made the trick.

**Comment by balupton** [comment]
I will only be able to have time to release this end of march, which is too long. I'm happy to add you as a maintainer so you can do the release sooner. Let me know.

**Comment by cattermo** [comment]
> I will only be able to have time to review and release this end of march, which is too long. I'm happy to add you as a maintainer so you can do the release sooner. Let me know.

I can make the release, no problem. Please add me 😊

**Comment by balupton** [comment]
Invite sent. For release, follow the guide in CONTRIBUTING.md once merged.

**Comment by cattermo** [comment]
> Invite sent. For release, follow the guide in CONTRIBUTING.md once merged. The npm release will occur via the cloud...
> 
> Actually, I'm not sure the DocPad org has been moved from Travis to GitHub Actions yet... if it is still on Travis (which killed our plan), then I can npm owner add you directly for the meantime and you can push the release manually. I'll need your npm username for that - and in late March or April then I can work on using `bevry/boundation` to mass migrate DocPad's repos to GitHub Actions.

Looks like I have to push it manually yes, npm username: cattermo

**Comment by balupton** [comment]
Turns out I don't have permission either, @10xLaCroixDrinker can you run the following please:

``` bash
npm owner add balupton docpad-plugin-nodesass
npm owner add bevryme docpad-plugin-nodesass
npm owner add cattermo docpad-plugin-nodesass
```

Thank you.

**Comment by 10xLaCroixDrinker** [comment]
I’m getting some errors with this. I need to open a support ticket with npm. I’ll update here when it’s resolved.

**Comment by balupton** [comment]
@cattermo for the meantime, I've created a `docpad` npm org, which you would have gotten an email invite to, you could publish this as `@docpad/docpad-plugin-nodesass`.

Support for such naming (trimming of org prefixes, ie. `@docpad/`) may need to be added into the docpad core or plugin loader / fetcher packages, wherever it is. I could add such support myself end of March.

Update: seems work is already done for such functionality, it just needs to be integrated into DocPad core perhaps: https://github.com/docpad/docpad/issues/691#issuecomment-418196719

**Comment by 10xLaCroixDrinker** [comment]
Done!

**Comment by balupton** [comment]
Just a heads up @cattermo and @docpad/extras-team @docpad/core-team  in case you received an email from npm.

I'll be running https://github.com/bevry/boundation on all docpad packages in the coming weeks, which will update all the projects to use a consistent release flow, of which the npm bot account `bevryme` will be the sole publisher of the docpad packages which will occur via CI (as such in case a maintainer gets hacked/compromised, they won't be able to publish any releases on the sneak - all all releases must go through the ci, and thus are deterministic). This is to ensure we meet the tidelift security standards.

As such, prior lingering npm authors may get emails or alerts as the changes roll out. Note that the package.json maintainers/contributors will be unphased. So accreditation is unaffected.

**Pull request merged**
